<?php

use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\FeatureTestTrait;

/** @internal */
final class ActivityRuleMenuTest extends CIUnitTestCase
{
    use FeatureTestTrait;
    private int $periodId;
    private int $previousPeriodId;
    private int $programId;
    private int $activityTypeId;

    protected function setUp(): void
    {
        parent::setUp(); $this->db = db_connect(); $forge = Config\Database::forge('tests');
        foreach (['academic_activities','activity_rules','audit_logs','activity_types','study_programs','academic_periods','academic_years'] as $table) $forge->dropTable($table,true);
        $forge->addField(['id'=>['type'=>'INTEGER','auto_increment'=>true],'code'=>['type'=>'VARCHAR','constraint'=>20],'start_year'=>['type'=>'INTEGER'],'end_year'=>['type'=>'INTEGER'],'is_active'=>['type'=>'INTEGER','default'=>1]]); $forge->addKey('id',true); $forge->createTable('academic_years');
        $forge->addField(['id'=>['type'=>'INTEGER','auto_increment'=>true],'academic_year_id'=>['type'=>'INTEGER'],'semester_code'=>['type'=>'VARCHAR','constraint'=>20],'start_date'=>['type'=>'DATE','null'=>true],'end_date'=>['type'=>'DATE','null'=>true],'is_active'=>['type'=>'INTEGER','default'=>1]]); $forge->addKey('id',true); $forge->createTable('academic_periods');
        $forge->addField(['id'=>['type'=>'INTEGER','auto_increment'=>true],'code'=>['type'=>'VARCHAR','constraint'=>20],'name'=>['type'=>'VARCHAR','constraint'=>150],'degree_level'=>['type'=>'VARCHAR','constraint'=>20],'is_active'=>['type'=>'INTEGER','default'=>1]]); $forge->addKey('id',true); $forge->createTable('study_programs');
        $forge->addField(['id'=>['type'=>'INTEGER','auto_increment'=>true],'code'=>['type'=>'VARCHAR','constraint'=>30],'name'=>['type'=>'VARCHAR','constraint'=>100],'examiner_supported'=>['type'=>'INTEGER','default'=>1],'is_active'=>['type'=>'INTEGER','default'=>1]]); $forge->addKey('id',true); $forge->createTable('activity_types');
        $forge->addField(['id'=>['type'=>'INTEGER','auto_increment'=>true],'academic_period_id'=>['type'=>'INTEGER'],'study_program_id'=>['type'=>'INTEGER'],'activity_type_id'=>['type'=>'INTEGER'],'min_supervisors'=>['type'=>'INTEGER'],'max_supervisors'=>['type'=>'INTEGER'],'min_examiners'=>['type'=>'INTEGER'],'max_examiners'=>['type'=>'INTEGER'],'examiner_optional'=>['type'=>'INTEGER','default'=>0],'is_active'=>['type'=>'INTEGER','default'=>1],'notes'=>['type'=>'TEXT','null'=>true],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]); $forge->addKey('id',true); $forge->createTable('activity_rules');
        $forge->addField(['id'=>['type'=>'INTEGER','auto_increment'=>true],'academic_period_id'=>['type'=>'INTEGER'],'study_program_id'=>['type'=>'INTEGER'],'activity_type_id'=>['type'=>'INTEGER']]); $forge->addKey('id',true); $forge->createTable('academic_activities');
        $forge->addField(['id'=>['type'=>'INTEGER','auto_increment'=>true],'user_id'=>['type'=>'INTEGER','null'=>true],'action'=>['type'=>'VARCHAR','constraint'=>100],'entity_type'=>['type'=>'VARCHAR','constraint'=>100],'entity_id'=>['type'=>'INTEGER'],'old_values'=>['type'=>'TEXT','null'=>true],'new_values'=>['type'=>'TEXT','null'=>true],'ip_address'=>['type'=>'VARCHAR','constraint'=>45,'null'=>true],'created_at'=>['type'=>'DATETIME','null'=>true]]); $forge->addKey('id',true); $forge->createTable('audit_logs');
        $this->db->table('academic_years')->insert(['code'=>'2026/2027','start_year'=>2026,'end_year'=>2027,'is_active'=>1]); $yearId=(int)$this->db->insertID();
        $this->db->table('academic_periods')->insert(['academic_year_id'=>$yearId,'semester_code'=>'GANJIL','is_active'=>0]); $this->previousPeriodId=(int)$this->db->insertID();
        $this->db->table('academic_periods')->insert(['academic_year_id'=>$yearId,'semester_code'=>'GENAP','is_active'=>1]); $this->periodId=(int)$this->db->insertID();
        $this->db->table('study_programs')->insert(['code'=>'SI','name'=>'Sistem Informasi','degree_level'=>'S1','is_active'=>1]); $this->programId=(int)$this->db->insertID();
        $this->db->table('activity_types')->insert(['code'=>'PROPOSAL','name'=>'Seminar Proposal','examiner_supported'=>1,'is_active'=>1]); $this->activityTypeId=(int)$this->db->insertID();
    }

    protected function tearDown(): void { $forge=Config\Database::forge('tests'); foreach (['academic_activities','activity_rules','audit_logs','activity_types','study_programs','academic_periods','academic_years'] as $table) $forge->dropTable($table,true); parent::tearDown(); }
    public function testGuestIsRedirected(): void { $this->get('/aturan-kegiatan')->assertRedirectTo(site_url('login')); }
    public function testAdminCanOpenModalAngularPage(): void { $result=$this->adminRequest()->get('/aturan-kegiatan'); $result->assertStatus(200); $body=$result->getBody(); $this->assertStringContainsString('ng-controller="aturanKegiatanController"',$body); $this->assertStringContainsString('id="activityRuleModal"',$body); $this->assertStringContainsString('id="copyActivityRuleModal"',$body); $this->assertStringContainsString('Salin periode sebelumnya',$body); $this->assertStringContainsString('Simpan aturan',$body); }
    public function testCreateRule(): void { $result=$this->mutationRequest()->post('/aturan-kegiatan/post',$this->payload()); $result->assertStatus(201); $payload=json_decode((string)$result->getJSON(),true); $this->assertSame(2,(int)$payload['data']['max_supervisors']); $this->assertSame(1,$this->db->table('audit_logs')->where('action','ACTIVITY_RULE_CREATED')->countAllResults()); }
    public function testReadOnlyReturnsRulesForActivePeriod(): void { $source=$this->payload(); $source['academic_period_id']=$this->previousPeriodId; $this->insertRule($source); $this->insertRule($this->payload()); $result=$this->adminRequest()->get('/aturan-kegiatan/read'); $result->assertStatus(200); $data=json_decode((string)$result->getJSON(),true)['data']; $this->assertCount(1,$data['rules']); $this->assertSame($this->periodId,(int)$data['rules'][0]['academic_period_id']); $this->assertSame($this->periodId,(int)$data['activePeriod']['id']); $this->assertCount(1,$data['previousPeriods']); }
    public function testCopyPreviousCopiesRulesAndSkipsExistingCombinations(): void { $source=$this->payload(); $source['academic_period_id']=$this->previousPeriodId; $this->insertRule($source); $result=$this->mutationRequest()->post('/aturan-kegiatan/copy-previous',['source_period_id'=>$this->previousPeriodId]); $result->assertStatus(200); $data=json_decode((string)$result->getJSON(),true)['data']; $this->assertSame(1,$data['created']); $this->assertSame(0,$data['skipped']); $second=$this->mutationRequest()->post('/aturan-kegiatan/copy-previous',['source_period_id'=>$this->previousPeriodId]); $second->assertStatus(200); $secondData=json_decode((string)$second->getJSON(),true)['data']; $this->assertSame(0,$secondData['created']); $this->assertSame(1,$secondData['skipped']); $this->assertSame(1,$this->db->table('activity_rules')->where('academic_period_id',$this->periodId)->countAllResults()); $this->assertSame(1,$this->db->table('audit_logs')->where('action','ACTIVITY_RULE_COPIED')->countAllResults()); }
    public function testDuplicateCombinationIsRejected(): void { $this->mutationRequest()->post('/aturan-kegiatan/post',$this->payload())->assertStatus(201); $result=$this->mutationRequest()->post('/aturan-kegiatan/post',$this->payload()); $result->assertStatus(422); $this->assertStringContainsString('kombinasi',json_decode((string)$result->getJSON(),true)['message']); }
    public function testExaminerIsRejectedWhenUnsupported(): void { $this->db->table('activity_types')->where('id',$this->activityTypeId)->update(['examiner_supported'=>0]); $result=$this->mutationRequest()->post('/aturan-kegiatan/post',$this->payload()); $result->assertStatus(422); $this->assertStringContainsString('tidak mendukung dosen penguji',json_decode((string)$result->getJSON(),true)['message']); }
    public function testDeleteRejectsRuleUsedByActivity(): void { $this->mutationRequest()->post('/aturan-kegiatan/post',$this->payload())->assertStatus(201); $id=(int)$this->db->table('activity_rules')->get()->getRow('id'); $this->db->table('academic_activities')->insert(['academic_period_id'=>$this->periodId,'study_program_id'=>$this->programId,'activity_type_id'=>$this->activityTypeId]); $result=$this->mutationRequest()->delete('/aturan-kegiatan/delete/'.$id); $result->assertStatus(422); $this->assertStringContainsString('kegiatan mahasiswa',json_decode((string)$result->getJSON(),true)['message']); }
    private function payload(): array { return ['academic_period_id'=>$this->periodId,'study_program_id'=>$this->programId,'activity_type_id'=>$this->activityTypeId,'min_supervisors'=>1,'max_supervisors'=>2,'min_examiners'=>1,'max_examiners'=>2,'examiner_optional'=>false,'is_active'=>true,'notes'=>'Aturan proposal']; }
    private function insertRule(array $data): int { $this->db->table('activity_rules')->insert($data); return (int)$this->db->insertID(); }
    private function adminRequest(): self { return $this->withSession(['auth'=>['id'=>1,'username'=>'admin','full_name'=>'Test Admin','role'=>'ADMIN']]); }
    private function mutationRequest(): self { helper('form'); return $this->adminRequest()->withHeaders([config('Security')->headerName=>csrf_hash()])->withBodyFormat('json'); }
}
