<?php

use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\FeatureTestTrait;

/** @internal */
final class PaymentVerificationMenuTest extends CIUnitTestCase
{
    use FeatureTestTrait;
    protected function setUp():void
    {
        parent::setUp();$this->db=db_connect();$f=Config\Database::forge('tests');foreach($this->tables() as $t)$f->dropTable($t,true);
        $this->table($f,'academic_years',['code'=>['type'=>'VARCHAR','constraint'=>20],'is_active'=>['type'=>'INTEGER']]);$this->table($f,'academic_periods',['academic_year_id'=>['type'=>'INTEGER'],'semester_code'=>['type'=>'VARCHAR','constraint'=>20],'is_active'=>['type'=>'INTEGER']]);$this->table($f,'activity_types',['code'=>['type'=>'VARCHAR','constraint'=>30],'name'=>['type'=>'VARCHAR','constraint'=>150]]);$this->table($f,'students',['nim'=>['type'=>'VARCHAR','constraint'=>30],'full_name'=>['type'=>'VARCHAR','constraint'=>150]]);$this->table($f,'payment_methods',['code'=>['type'=>'VARCHAR','constraint'=>30],'name'=>['type'=>'VARCHAR','constraint'=>100],'is_active'=>['type'=>'INTEGER']]);
        $this->table($f,'student_bills',['bill_no'=>['type'=>'VARCHAR','constraint'=>50],'student_id'=>['type'=>'INTEGER'],'academic_period_id'=>['type'=>'INTEGER'],'activity_type_id'=>['type'=>'INTEGER'],'total_amount'=>['type'=>'DECIMAL','constraint'=>'15,2'],'status'=>['type'=>'VARCHAR','constraint'=>25],'updated_at'=>['type'=>'DATETIME','null'=>true]]);
        $this->table($f,'student_payments',['payment_no'=>['type'=>'VARCHAR','constraint'=>50],'student_id'=>['type'=>'INTEGER'],'payment_method_id'=>['type'=>'INTEGER'],'payment_date'=>['type'=>'DATETIME'],'amount'=>['type'=>'DECIMAL','constraint'=>'15,2'],'reference_no'=>['type'=>'VARCHAR','constraint'=>100,'null'=>true],'proof_file_path'=>['type'=>'TEXT','null'=>true],'status'=>['type'=>'VARCHAR','constraint'=>20],'verified_at'=>['type'=>'DATETIME','null'=>true],'verified_by'=>['type'=>'INTEGER','null'=>true],'notes'=>['type'=>'TEXT','null'=>true],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]);
        $this->table($f,'student_payment_allocations',['student_payment_id'=>['type'=>'INTEGER'],'student_bill_id'=>['type'=>'INTEGER'],'allocated_amount'=>['type'=>'DECIMAL','constraint'=>'15,2'],'created_at'=>['type'=>'DATETIME','null'=>true]]);$this->table($f,'audit_logs',['user_id'=>['type'=>'INTEGER','null'=>true],'action'=>['type'=>'VARCHAR','constraint'=>100],'entity_type'=>['type'=>'VARCHAR','constraint'=>100],'entity_id'=>['type'=>'INTEGER'],'old_values'=>['type'=>'TEXT','null'=>true],'new_values'=>['type'=>'TEXT','null'=>true],'ip_address'=>['type'=>'VARCHAR','constraint'=>45,'null'=>true],'created_at'=>['type'=>'DATETIME','null'=>true]]);
        $this->db->table('academic_years')->insert(['code'=>'2026/2027','is_active'=>1]);$y=(int)$this->db->insertID();$this->db->table('academic_periods')->insert(['academic_year_id'=>$y,'semester_code'=>'GANJIL','is_active'=>1]);$p=(int)$this->db->insertID();$this->db->table('activity_types')->insert(['code'=>'SEM','name'=>'Seminar']);$a=(int)$this->db->insertID();$this->db->table('students')->insert(['nim'=>'2026001','full_name'=>'Mahasiswa Uji']);$this->student=(int)$this->db->insertID();$this->db->table('payment_methods')->insert(['code'=>'VA','name'=>'Virtual Account','is_active'=>1]);$this->method=(int)$this->db->insertID();$this->db->table('student_bills')->insert(['bill_no'=>'INV-001','student_id'=>$this->student,'academic_period_id'=>$p,'activity_type_id'=>$a,'total_amount'=>150000,'status'=>'BELUM_DIBAYAR']);$this->bill=(int)$this->db->insertID();
    }
    protected function tearDown():void{$f=Config\Database::forge('tests');foreach($this->tables() as $t)$f->dropTable($t,true);parent::tearDown();}
    public function testPageHasRecordingAndVerificationModals():void{$body=$this->admin()->get('/keuangan/verifikasi')->getBody();$this->assertStringContainsString('ng-controller="verifikasiPembayaranController"',$body);$this->assertStringContainsString('id="paymentModal"',$body);$this->assertStringContainsString('id="rejectPaymentModal"',$body);}
    public function testRecordAndAcceptFullPaymentMakesBillPaid():void{$created=$this->mutation()->post('/keuangan/verifikasi/post',$this->payload(150000));$created->assertStatus(201);$id=(int)json_decode((string)$created->getJSON(),true)['data']['id'];$this->assertSame('MENUNGGU',$this->db->table('student_bills')->where('id',$this->bill)->get()->getRow('status'));$this->mutation()->post('/keuangan/verifikasi/terima/'.$id,[])->assertStatus(200);$this->assertSame('DITERIMA',$this->db->table('student_payments')->where('id',$id)->get()->getRow('status'));$this->assertSame('LUNAS',$this->db->table('student_bills')->where('id',$this->bill)->get()->getRow('status'));}
    public function testRejectedPaymentRestoresUnpaidStatus():void{$created=$this->mutation()->post('/keuangan/verifikasi/post',$this->payload(50000));$id=(int)json_decode((string)$created->getJSON(),true)['data']['id'];$this->mutation()->post('/keuangan/verifikasi/tolak/'.$id,['notes'=>'Nomor referensi tidak cocok'])->assertStatus(200);$this->assertSame('DITOLAK',$this->db->table('student_payments')->where('id',$id)->get()->getRow('status'));$this->assertSame('BELUM_DIBAYAR',$this->db->table('student_bills')->where('id',$this->bill)->get()->getRow('status'));}
    public function testOverpaymentIsRejected():void{$r=$this->mutation()->post('/keuangan/verifikasi/post',$this->payload(150001));$r->assertStatus(422);$this->assertStringContainsString('tidak melebihi sisa tagihan',json_decode((string)$r->getJSON(),true)['message']);}
    public function testReadReturnsPendingPaymentAndOutstandingBill():void{$this->mutation()->post('/keuangan/verifikasi/post',$this->payload(50000))->assertStatus(201);$r=$this->admin()->get('/keuangan/verifikasi/read');$r->assertStatus(200);$data=json_decode((string)$r->getJSON(),true)['data'];$this->assertSame('MENUNGGU',$data['payments'][0]['status']);$this->assertSame(150000,(int)$data['bills'][0]['total_amount']);}
    private function payload(int $amount):array{return['student_bill_id'=>$this->bill,'payment_method_id'=>$this->method,'payment_date'=>'2026-09-01T10:00','amount'=>$amount,'reference_no'=>'REF-001'];}private function tables():array{return['audit_logs','student_payment_allocations','student_payments','student_bills','payment_methods','students','activity_types','academic_periods','academic_years'];}private function table($f,string $n,array $x):void{$f->addField(array_merge(['id'=>['type'=>'INTEGER','auto_increment'=>true]],$x));$f->addKey('id',true);$f->createTable($n);}private function admin():self{return$this->withSession(['auth'=>['id'=>1,'role'=>'ADMIN','username'=>'admin','full_name'=>'Admin']]);}private function mutation():self{helper('form');return$this->admin()->withHeaders([config('Security')->headerName=>csrf_hash()])->withBodyFormat('json');}
}
