<?php

use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\FeatureTestTrait;

/** @internal */
final class StudentBillMenuTest extends CIUnitTestCase
{
    use FeatureTestTrait;

    protected function setUp():void
    {
        parent::setUp();$this->db=db_connect();$f=Config\Database::forge('tests');foreach($this->tables() as $t)$f->dropTable($t,true);
        $this->table($f,'academic_years',['code'=>['type'=>'VARCHAR','constraint'=>20],'name'=>['type'=>'VARCHAR','constraint'=>100],'is_active'=>['type'=>'INTEGER','default'=>1]]);
        $this->table($f,'academic_periods',['academic_year_id'=>['type'=>'INTEGER'],'semester_code'=>['type'=>'VARCHAR','constraint'=>20],'is_active'=>['type'=>'INTEGER','default'=>1]]);
        $this->table($f,'study_programs',['code'=>['type'=>'VARCHAR','constraint'=>20],'name'=>['type'=>'VARCHAR','constraint'=>150],'is_active'=>['type'=>'INTEGER','default'=>1]]);
        $this->table($f,'activity_types',['code'=>['type'=>'VARCHAR','constraint'=>30],'name'=>['type'=>'VARCHAR','constraint'=>150],'is_active'=>['type'=>'INTEGER','default'=>1]]);
        $this->table($f,'exam_paths',['code'=>['type'=>'VARCHAR','constraint'=>20],'name'=>['type'=>'VARCHAR','constraint'=>100],'is_active'=>['type'=>'INTEGER','default'=>1],'sort_order'=>['type'=>'INTEGER','default'=>1]]);
        $this->table($f,'students',['nim'=>['type'=>'VARCHAR','constraint'=>30],'full_name'=>['type'=>'VARCHAR','constraint'=>150],'study_program_id'=>['type'=>'INTEGER'],'status'=>['type'=>'VARCHAR','constraint'=>20]]);
        $this->table($f,'lecturers',['nidn'=>['type'=>'VARCHAR','constraint'=>30,'null'=>true],'full_name'=>['type'=>'VARCHAR','constraint'=>150],'is_active'=>['type'=>'INTEGER','default'=>1]]);
        $this->table($f,'academic_activities',['activity_no'=>['type'=>'VARCHAR','constraint'=>50],'student_id'=>['type'=>'INTEGER'],'academic_period_id'=>['type'=>'INTEGER'],'study_program_id'=>['type'=>'INTEGER'],'activity_type_id'=>['type'=>'INTEGER'],'exam_path_id'=>['type'=>'INTEGER'],'title'=>['type'=>'VARCHAR','constraint'=>500,'null'=>true],'scheduled_at'=>['type'=>'DATETIME','null'=>true],'status'=>['type'=>'VARCHAR','constraint'=>20]]);
        $this->table($f,'fee_settings',['academic_period_id'=>['type'=>'INTEGER'],'study_program_id'=>['type'=>'INTEGER'],'activity_type_id'=>['type'=>'INTEGER'],'exam_path_id'=>['type'=>'INTEGER'],'version_no'=>['type'=>'INTEGER'],'is_active'=>['type'=>'INTEGER'],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]);
        $this->table($f,'fee_setting_items',['fee_setting_id'=>['type'=>'INTEGER'],'item_code'=>['type'=>'VARCHAR','constraint'=>40],'item_name'=>['type'=>'VARCHAR','constraint'=>150],'amount'=>['type'=>'DECIMAL','constraint'=>'15,2'],'is_required'=>['type'=>'INTEGER'],'sort_order'=>['type'=>'INTEGER'],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]);
        $this->table($f,'activity_assignments',['activity_id'=>['type'=>'INTEGER'],'lecturer_id'=>['type'=>'INTEGER'],'role_type'=>['type'=>'VARCHAR','constraint'=>20],'position_no'=>['type'=>'INTEGER'],'status'=>['type'=>'VARCHAR','constraint'=>20]]);
        $this->table($f,'honor_rate_settings',['academic_period_id'=>['type'=>'INTEGER'],'study_program_id'=>['type'=>'INTEGER','null'=>true],'activity_type_id'=>['type'=>'INTEGER'],'role_type'=>['type'=>'VARCHAR','constraint'=>20],'position_no'=>['type'=>'INTEGER'],'gross_amount'=>['type'=>'DECIMAL','constraint'=>'15,2'],'tax_rate_percent'=>['type'=>'DECIMAL','constraint'=>'7,4'],'version_no'=>['type'=>'INTEGER'],'is_active'=>['type'=>'INTEGER']]);
        $this->table($f,'honor_entitlements',['assignment_id'=>['type'=>'INTEGER'],'honor_rate_setting_id'=>['type'=>'INTEGER'],'gross_amount_snapshot'=>['type'=>'DECIMAL','constraint'=>'15,2'],'tax_rate_snapshot'=>['type'=>'DECIMAL','constraint'=>'7,4'],'tax_amount'=>['type'=>'DECIMAL','constraint'=>'15,2'],'net_amount'=>['type'=>'DECIMAL','constraint'=>'15,2'],'status'=>['type'=>'VARCHAR','constraint'=>25],'notes'=>['type'=>'TEXT','null'=>true],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]);
        $this->table($f,'student_bills',['bill_no'=>['type'=>'VARCHAR','constraint'=>50],'student_id'=>['type'=>'INTEGER'],'activity_id'=>['type'=>'INTEGER'],'fee_setting_id'=>['type'=>'INTEGER'],'academic_period_id'=>['type'=>'INTEGER'],'study_program_id'=>['type'=>'INTEGER'],'activity_type_id'=>['type'=>'INTEGER'],'exam_path_id'=>['type'=>'INTEGER'],'bill_date'=>['type'=>'DATE'],'due_date'=>['type'=>'DATE','null'=>true],'subtotal_amount'=>['type'=>'DECIMAL','constraint'=>'15,2'],'discount_amount'=>['type'=>'DECIMAL','constraint'=>'15,2','default'=>0],'penalty_amount'=>['type'=>'DECIMAL','constraint'=>'15,2','default'=>0],'total_amount'=>['type'=>'DECIMAL','constraint'=>'15,2'],'status'=>['type'=>'VARCHAR','constraint'=>25],'notes'=>['type'=>'TEXT','null'=>true],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]);
        $this->table($f,'student_bill_items',['student_bill_id'=>['type'=>'INTEGER'],'fee_setting_item_id'=>['type'=>'INTEGER','null'=>true],'item_code_snapshot'=>['type'=>'VARCHAR','constraint'=>40],'item_name_snapshot'=>['type'=>'VARCHAR','constraint'=>150],'amount_snapshot'=>['type'=>'DECIMAL','constraint'=>'15,2'],'discount_amount'=>['type'=>'DECIMAL','constraint'=>'15,2','default'=>0],'total_amount'=>['type'=>'DECIMAL','constraint'=>'15,2'],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]);
        $this->table($f,'payment_methods',['code'=>['type'=>'VARCHAR','constraint'=>30],'name'=>['type'=>'VARCHAR','constraint'=>100],'is_active'=>['type'=>'INTEGER']]);
        $this->table($f,'student_payments',['payment_no'=>['type'=>'VARCHAR','constraint'=>50],'student_id'=>['type'=>'INTEGER'],'payment_method_id'=>['type'=>'INTEGER'],'payment_date'=>['type'=>'DATETIME'],'amount'=>['type'=>'DECIMAL','constraint'=>'15,2'],'reference_no'=>['type'=>'VARCHAR','constraint'=>100,'null'=>true],'status'=>['type'=>'VARCHAR','constraint'=>20]]);
        $this->table($f,'student_payment_allocations',['student_payment_id'=>['type'=>'INTEGER'],'student_bill_id'=>['type'=>'INTEGER'],'allocated_amount'=>['type'=>'DECIMAL','constraint'=>'15,2'],'created_at'=>['type'=>'DATETIME','null'=>true]]);
        $this->auditTable($f);
        $this->seed();
    }
    protected function tearDown():void{$f=Config\Database::forge('tests');foreach($this->tables() as $t)$f->dropTable($t,true);parent::tearDown();}
    public function testPageUsesAngularModal():void{$body=$this->admin()->get('/keuangan/tagihan')->getBody();$this->assertStringContainsString('ng-controller="tagihanMahasiswaController"',$body);$this->assertStringContainsString('id="billModal"',$body);$this->assertStringContainsString('Terbitkan tagihan',$body);}
    public function testCreateBillLocksFeeItems():void{$r=$this->mutation()->post('/keuangan/tagihan/post',['activity_id'=>$this->activity,'due_date'=>'2026-10-01']);$r->assertStatus(201);$bill=$this->db->table('student_bills')->get()->getRowArray();$this->assertSame('150000',(string)(int)$bill['total_amount']);$this->assertSame('BELUM_DIBAYAR',$bill['status']);$this->assertCount(2,$this->db->table('student_bill_items')->where('student_bill_id',$bill['id'])->get()->getResultArray());}
    public function testDuplicateBillIsRejected():void{$this->mutation()->post('/keuangan/tagihan/post',['activity_id'=>$this->activity])->assertStatus(201);$r=$this->mutation()->post('/keuangan/tagihan/post',['activity_id'=>$this->activity]);$r->assertStatus(422);$this->assertStringContainsString('sudah memiliki tagihan',json_decode((string)$r->getJSON(),true)['message']);}
    public function testDueDateDefaultsToOneDayBeforeSchedule():void{$this->mutation()->post('/keuangan/tagihan/post',['activity_id'=>$this->activity])->assertStatus(201);$this->assertSame('2026-09-09',$this->db->table('student_bills')->get()->getRow('due_date'));}
    public function testReadReturnsBillForActivePeriod():void{$this->mutation()->post('/keuangan/tagihan/post',['activity_id'=>$this->activity])->assertStatus(201);$r=$this->admin()->get('/keuangan/tagihan/read');$r->assertStatus(200);$data=json_decode((string)$r->getJSON(),true)['data'];$this->assertCount(1,$data['bills']);$this->assertCount(0,$data['activities']);}
    public function testPreviewShowsRequiredAndOptionalComponents():void{$r=$this->admin()->get('/keuangan/tagihan/preview/'.$this->activity);$r->assertStatus(200);$items=json_decode((string)$r->getJSON(),true)['data']['items'];$this->assertCount(2,$items);$this->assertTrue($items[0]['is_required']);$this->assertFalse($items[1]['is_required']);}
    public function testOptionalComponentCanBeExcluded():void{$this->mutation()->post('/keuangan/tagihan/post',['activity_id'=>$this->activity,'selected_item_ids'=>[$this->requiredItem]])->assertStatus(201);$bill=$this->db->table('student_bills')->get()->getRowArray();$this->assertSame(100000,(int)$bill['total_amount']);$this->assertSame(1,$this->db->table('student_bill_items')->where('student_bill_id',$bill['id'])->countAllResults());}
    public function testRequiredComponentCannotBeExcluded():void{$r=$this->mutation()->post('/keuangan/tagihan/post',['activity_id'=>$this->activity,'selected_item_ids'=>[$this->optionalItem]]);$r->assertStatus(422);$this->assertStringContainsString('Komponen wajib tidak dapat dihilangkan',json_decode((string)$r->getJSON(),true)['message']);}
    public function testBillUsesFeeForSelectedExamPath():void{$this->db->table('exam_paths')->insert(['code'=>'JURNAL','name'=>'Jurnal','is_active'=>1,'sort_order'=>2]);$jurnal=(int)$this->db->insertID();$activity=$this->db->table('academic_activities')->where('id',$this->activity)->get()->getRowArray();$this->db->table('academic_activities')->where('id',$this->activity)->update(['exam_path_id'=>$jurnal]);$this->db->table('fee_settings')->insert(['academic_period_id'=>$activity['academic_period_id'],'study_program_id'=>$activity['study_program_id'],'activity_type_id'=>$activity['activity_type_id'],'exam_path_id'=>$jurnal,'version_no'=>1,'is_active'=>1]);$fee=(int)$this->db->insertID();$this->db->table('fee_setting_items')->insert(['fee_setting_id'=>$fee,'item_code'=>'JURNAL','item_name'=>'Tarif Jalur Jurnal','amount'=>275000,'is_required'=>1,'sort_order'=>1]);$this->mutation()->post('/keuangan/tagihan/post',['activity_id'=>$this->activity])->assertStatus(201);$this->assertSame(275000,(int)$this->db->table('student_bills')->get()->getRow('total_amount'));$this->assertSame($jurnal,(int)$this->db->table('student_bills')->get()->getRow('exam_path_id'));}
    public function testCreatingBillAutomaticallyCreatesHonorEntitlement():void{$r=$this->mutation()->post('/keuangan/tagihan/post',['activity_id'=>$this->activity]);$r->assertStatus(201);$payload=json_decode((string)$r->getJSON(),true);$this->assertSame(1,(int)$payload['data']['honor_entitlement_count']);$entitlement=$this->db->table('honor_entitlements')->get()->getRowArray();$this->assertSame('DIAJUKAN',$entitlement['status']);$this->assertSame(50000,(int)$entitlement['tax_amount']);$this->assertSame(950000,(int)$entitlement['net_amount']);}
    public function testMissingHonorRatePreventsBillForAssignedLecturer():void{$this->db->table('honor_rate_settings')->where('id >',0)->delete();$r=$this->mutation()->post('/keuangan/tagihan/post',['activity_id'=>$this->activity]);$r->assertStatus(422);$this->assertStringContainsString('Tarif honor untuk Dosen Uji',json_decode((string)$r->getJSON(),true)['message']);$this->assertSame(0,$this->db->table('student_bills')->countAllResults());}
    private function seed():void{$this->db->table('academic_years')->insert(['code'=>'2026/2027','name'=>'2026/2027','is_active'=>1]);$y=(int)$this->db->insertID();$this->db->table('academic_periods')->insert(['academic_year_id'=>$y,'semester_code'=>'GANJIL','is_active'=>1]);$this->period=(int)$this->db->insertID();$this->db->table('study_programs')->insert(['code'=>'TI','name'=>'Teknik Informatika','is_active'=>1]);$p=(int)$this->db->insertID();$this->db->table('activity_types')->insert(['code'=>'SEMINAR','name'=>'Seminar Proposal','is_active'=>1]);$a=(int)$this->db->insertID();$this->db->table('exam_paths')->insert(['code'=>'UMUM','name'=>'Umum','is_active'=>1,'sort_order'=>1]);$this->examPath=(int)$this->db->insertID();$this->db->table('students')->insert(['nim'=>'2026001','full_name'=>'Mahasiswa Uji','study_program_id'=>$p,'status'=>'AKTIF']);$s=(int)$this->db->insertID();$this->db->table('lecturers')->insert(['nidn'=>'001','full_name'=>'Dosen Uji','is_active'=>1]);$lecturer=(int)$this->db->insertID();$this->db->table('academic_activities')->insert(['activity_no'=>'KGT-001','student_id'=>$s,'academic_period_id'=>$this->period,'study_program_id'=>$p,'activity_type_id'=>$a,'exam_path_id'=>$this->examPath,'title'=>'Seminar','scheduled_at'=>'2026-09-10 09:00:00','status'=>'TERJADWAL']);$this->activity=(int)$this->db->insertID();$this->db->table('activity_assignments')->insert(['activity_id'=>$this->activity,'lecturer_id'=>$lecturer,'role_type'=>'PEMBIMBING','position_no'=>1,'status'=>'AKTIF']);$this->assignment=(int)$this->db->insertID();$this->db->table('honor_rate_settings')->insert(['academic_period_id'=>$this->period,'study_program_id'=>$p,'activity_type_id'=>$a,'role_type'=>'PEMBIMBING','position_no'=>1,'gross_amount'=>1000000,'tax_rate_percent'=>5,'version_no'=>1,'is_active'=>1]);$this->db->table('fee_settings')->insert(['academic_period_id'=>$this->period,'study_program_id'=>$p,'activity_type_id'=>$a,'exam_path_id'=>$this->examPath,'version_no'=>1,'is_active'=>1]);$fee=(int)$this->db->insertID();$this->db->table('fee_setting_items')->insert(['fee_setting_id'=>$fee,'item_code'=>'POKOK','item_name'=>'Tarif Pokok','amount'=>100000,'is_required'=>1,'sort_order'=>1]);$this->requiredItem=(int)$this->db->insertID();$this->db->table('fee_setting_items')->insert(['fee_setting_id'=>$fee,'item_code'=>'ADM','item_name'=>'Administrasi Opsional','amount'=>50000,'is_required'=>0,'sort_order'=>2]);$this->optionalItem=(int)$this->db->insertID();}
    private function tables():array{return['audit_logs','student_payment_allocations','student_payments','payment_methods','honor_entitlements','honor_rate_settings','activity_assignments','student_bill_items','student_bills','fee_setting_items','fee_settings','academic_activities','lecturers','students','exam_paths','activity_types','study_programs','academic_periods','academic_years'];}
    private function table($f,string $n,array $x):void{$f->addField(array_merge(['id'=>['type'=>'INTEGER','auto_increment'=>true]],$x));$f->addKey('id',true);$f->createTable($n);}private function auditTable($f):void{$this->table($f,'audit_logs',['user_id'=>['type'=>'INTEGER','null'=>true],'action'=>['type'=>'VARCHAR','constraint'=>100],'entity_type'=>['type'=>'VARCHAR','constraint'=>100],'entity_id'=>['type'=>'INTEGER'],'old_values'=>['type'=>'TEXT','null'=>true],'new_values'=>['type'=>'TEXT','null'=>true],'ip_address'=>['type'=>'VARCHAR','constraint'=>45,'null'=>true],'created_at'=>['type'=>'DATETIME','null'=>true]]);}private function admin():self{return$this->withSession(['auth'=>['id'=>1,'role'=>'ADMIN','username'=>'admin','full_name'=>'Admin']]);}private function mutation():self{helper('form');return$this->admin()->withHeaders([config('Security')->headerName=>csrf_hash()])->withBodyFormat('json');}
}
