<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<?= $this->include('pages/partials/page_heading') ?>
<section ng-controller="batchHonorController" ng-cloak>
    <div class="alert alert-danger" ng-if="errorMessage" ng-bind="errorMessage"></div>
    <div class="alert alert-success" ng-if="successMessage" ng-bind="successMessage"></div>
    <div class="row g-3">
        <div class="col-xl-5"><article class="card sitara-card">
            <header class="card-header d-flex justify-content-between align-items-start gap-3"><div><h2 class="sitara-card-title">Hak siap dibayar</h2><p class="sitara-card-subtitle mb-0">Pilih hak honor yang telah disetujui.</p><small ng-if="selectedIds().length" ng-bind="selectedIds().length+' hak dipilih · '+rupiah(selectedTotal())"></small></div><button class="btn btn-sm btn-primary text-nowrap" ng-click="create()" ng-disabled="working||!selectedIds().length" ng-bind="working?'Memproses...':'Buat batch'"></button></header>
            <div class="table-responsive"><table class="table sitara-table mb-0"><thead><tr><th><input type="checkbox" ng-checked="allSelected()" ng-click="toggleAll()"></th><th>Dosen dan kegiatan</th><th class="text-end">Bersih</th></tr></thead><tbody><tr ng-repeat="x in entitlements"><td><input type="checkbox" ng-checked="selected[x.id]" ng-click="toggle(x.id)"></td><td><div class="table-main" ng-bind="x.full_name"></div><small ng-bind="x.activity_name+' · '+x.role_type+' '+x.position_no"></small></td><td class="text-end" ng-bind="rupiah(x.net_amount)"></td></tr><tr ng-if="!entitlements.length"><td colspan="3" class="sitara-empty">Belum ada hak honor yang siap dibayar.</td></tr></tbody></table></div>
        </article></div>
        <div class="col-xl-7"><article class="card sitara-card">
            <header class="card-header"><h2 class="sitara-card-title">Batch pembayaran</h2><p class="sitara-card-subtitle mb-0">Periksa detail, ekspor Excel, lalu tandai pembayaran.</p></header>
            <div class="table-responsive"><table class="table sitara-table mb-0"><thead><tr><th>Batch</th><th>Dosen</th><th class="text-end">Bersih</th><th>Status</th><th>Aksi</th></tr></thead><tbody><tr ng-repeat="x in datas"><td><div class="table-main" ng-bind="x.batch_no"></div><small ng-bind="x.payment_date||'Belum dibayar'"></small></td><td ng-bind="x.lecturer_count"></td><td class="text-end table-main" ng-bind="rupiah(x.net_total)"></td><td ng-bind="x.status"></td><td><div class="sitara-row-actions"><button class="btn btn-sm btn-outline-primary" ng-click="detail(x)">Detail</button><a class="btn btn-sm btn-outline-primary" ng-href="{{exportUrl(x)}}">Excel</a><button class="btn btn-sm btn-outline-success" ng-if="x.status==='DRAFT'" ng-click="openPay(x)">Bayar</button></div></td></tr><tr ng-if="!datas.length"><td colspan="5" class="sitara-empty">Belum ada batch pembayaran.</td></tr></tbody></table></div>
        </article></div>
    </div>
    <div class="modal fade" id="payHonorModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form name="payForm" ng-submit="pay(payForm)"><div class="modal-header"><h2 class="modal-title h5">Bayarkan batch honor</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Metode pembayaran</label><select class="form-select mb-3" ng-model="payModel.payment_method_id" required><option value="">Pilih metode</option><option ng-repeat="x in methods" ng-value="x.id" ng-bind="x.code+' — '+x.name"></option></select><label class="form-label">Tanggal pembayaran</label><input type="date" class="form-control mb-3" ng-model="payModel.payment_date" required><label class="form-label">Nomor referensi</label><input class="form-control" maxlength="100" ng-model="payModel.reference_no"><small class="text-muted">Opsional; dapat diisi nomor transaksi bank atau nomor kuitansi.</small></div><div class="modal-footer"><button class="btn btn-outline-gray" type="button" data-bs-dismiss="modal">Batal</button><button class="btn btn-success" ng-disabled="working">Tandai dibayar</button></div></form></div></div></div>
    <div class="modal fade" id="batchDetailModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><div><h2 class="modal-title h5" ng-bind="detailData.batch_no"></h2><small ng-bind="detailData.status+' · '+(detailData.payment_date||'Belum dibayar')"></small></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="table-responsive"><table class="table"><thead><tr><th>Dosen</th><th>Kegiatan</th><th>Peran</th><th>Rekening</th><th class="text-end">Bruto</th><th class="text-end">Pajak</th><th class="text-end">Bersih</th></tr></thead><tbody><tr ng-repeat="x in detailData.items"><td ng-bind="x.full_name"></td><td><div ng-bind="x.activity_no"></div><small ng-bind="x.activity_name"></small></td><td ng-bind="x.role_type+' '+x.position_no"></td><td ng-bind="(x.bank_name_snapshot||'-')+' · '+(x.bank_account_number_snapshot||'-')"></td><td class="text-end" ng-bind="rupiah(x.gross_amount)"></td><td class="text-end" ng-bind="rupiah(x.tax_amount)"></td><td class="text-end" ng-bind="rupiah(x.net_amount)"></td></tr></tbody></table></div></div><div class="modal-footer"><a class="btn btn-outline-primary" ng-href="{{exportUrl(detailData)}}">Export Excel</a><button class="btn btn-outline-gray" data-bs-dismiss="modal">Tutup</button></div></div></div></div>
</section>
<script>window.SITARA_HONOR_BATCH_CONFIG=<?= json_encode(['baseUrl'=>site_url('honor/pembayaran')]) ?>;window.SITARA_CSRF=<?= json_encode(['header'=>$csrfHeader,'hash'=>$csrfHash]) ?>;</script>
<?= $this->endSection() ?>
