<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<?= $this->include('pages/partials/page_heading') ?>
<section ng-controller="adminUserController" ng-cloak>
    <div class="alert alert-danger" ng-if="errorMessage" ng-bind="errorMessage"></div>
    <div class="alert alert-success" ng-if="successMessage" ng-bind="successMessage"></div>
    <article class="card sitara-card">
        <header class="card-header d-flex justify-content-between align-items-center"><div><h2 class="sitara-card-title">Pengguna sistem</h2><p class="sitara-card-subtitle">Kelola akun administrator, keuangan, dan operator Prodi.</p></div><button class="btn btn-sm btn-primary" ng-click="open()">Tambah pengguna</button></header>
        <div class="table-responsive"><table class="table sitara-table"><thead><tr><th>Nama</th><th>Username</th><th>Peran</th><th>Program studi</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody><tr ng-repeat="x in datas"><td class="table-main" ng-bind="x.full_name"></td><td ng-bind="x.username"></td><td ng-bind="x.role"></td><td ng-bind="programNames(x)"></td><td ng-bind="x.is_active?'Aktif':'Nonaktif'"></td><td><div class="sitara-row-actions justify-content-end"><button class="btn btn-sm btn-outline-primary" ng-click="open(x)">Ubah</button><button class="btn btn-sm btn-outline-warning" ng-click="openPassword(x)">Password</button></div></td></tr><tr ng-if="!datas.length"><td colspan="6" class="sitara-empty">Belum ada pengguna.</td></tr></tbody></table></div>
    </article>
    <div class="modal fade" id="adminUserModal"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form name="adminForm" ng-submit="save(adminForm)" novalidate><div class="modal-header"><h2 class="modal-title h5" ng-bind="model.id?'Ubah pengguna':'Tambah pengguna'"></h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Nama lengkap *</label><input class="form-control" ng-model="model.full_name" required></div><div class="col-md-6"><label class="form-label">Username *</label><input class="form-control" ng-model="model.username" required></div><div class="col-md-6"><label class="form-label">Email</label><input type="email" class="form-control" ng-model="model.email"></div><div class="col-md-6"><label class="form-label">Peran *</label><select class="form-select" ng-model="model.role" ng-options="role for role in roles" required></select></div><div class="col-md-6" ng-if="!model.id"><label class="form-label">Password awal *</label><input type="password" minlength="8" class="form-control" ng-model="model.password" required></div><div class="col-md-6" ng-if="model.role==='PRODI'"><label class="form-label">Program studi *</label><select class="form-select" multiple size="4" ng-model="model.study_program_ids" ng-options="p.id as (p.code+' — '+p.name) for p in programs" ng-required="model.role==='PRODI'"></select><small class="text-muted">Gunakan Ctrl/Command untuk memilih lebih dari satu.</small></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" id="adminActive" ng-model="model.is_active"><label class="form-check-label" for="adminActive">Akun aktif</label></div></div></div></div><div class="modal-footer"><button class="btn btn-outline-gray" type="button" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary" type="submit">Simpan pengguna</button></div></form></div></div></div>
    <div class="modal fade" id="adminPasswordModal"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form name="passwordForm" ng-submit="savePassword(passwordForm)" novalidate><div class="modal-header"><h2 class="modal-title h5">Ubah password</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><p ng-bind="passwordModel.name"></p><label class="form-label">Password baru *</label><input type="password" minlength="8" class="form-control" ng-model="passwordModel.password" required></div><div class="modal-footer"><button class="btn btn-primary" type="submit">Simpan password</button></div></form></div></div></div>
</section>
<script>window.SITARA_ADMIN_USER_CONFIG=<?= json_encode(['baseUrl'=>site_url('pengaturan/admin')]) ?>;window.SITARA_ADMIN_PROGRAMS=<?= json_encode($programs ?? []) ?>;window.SITARA_CSRF=<?= json_encode(['header'=>$csrfHeader,'hash'=>$csrfHash]) ?>;</script>
<?= $this->endSection() ?>
