<?= $this->extend('layouts/main') ?>
<?= $this->section('styles') ?><style>[ng-cloak]{display:none!important}</style><?= $this->endSection() ?>
<?= $this->section('content') ?>
<?= $this->include('pages/partials/page_heading') ?>
<section class="row g-3 align-items-start" ng-controller="metodePembayaranController" ng-cloak>
    <div class="col-12"><div class="alert alert-danger" ng-if="errorMessage" ng-bind="errorMessage"></div><div class="alert alert-success" ng-if="successMessage" ng-bind="successMessage"></div></div>
    <div class="col-12 col-xl-4"><article class="card sitara-card"><header class="card-header d-flex justify-content-between gap-3"><div><h2 class="sitara-card-title" ng-bind="model.id ? 'Ubah metode pembayaran' : 'Tambah metode pembayaran'"></h2><p class="sitara-card-subtitle">Metode aktif dapat dipilih pada transaksi mahasiswa dan honor.</p></div><button type="button" class="btn btn-sm btn-outline-gray" ng-if="model.id" ng-click="reset()">Batal</button></header><div class="card-body">
        <form name="paymentMethodForm" ng-submit="save(paymentMethodForm)" novalidate>
            <div class="mb-3"><label for="payment_method_code" class="form-label">Kode</label><input id="payment_method_code" name="code" class="form-control text-uppercase" maxlength="30" placeholder="TRANSFER" ng-model="model.code" required ng-pattern="/^[A-Za-z0-9._-]{2,30}$/"><div class="text-danger small mt-1" ng-if="paymentMethodForm.$submitted && paymentMethodForm.code.$invalid">Kode wajib diisi dengan format yang valid.</div></div>
            <div class="mb-3"><label for="payment_method_name" class="form-label">Nama metode</label><input id="payment_method_name" name="name" class="form-control" minlength="3" maxlength="100" placeholder="Transfer Bank" ng-model="model.name" required><div class="text-danger small mt-1" ng-if="paymentMethodForm.$submitted && paymentMethodForm.name.$invalid">Nama metode wajib diisi.</div></div>
            <div class="rounded border bg-gray-50 p-3 mb-3"><div class="form-check form-switch"><input id="payment_method_active" class="form-check-input" type="checkbox" ng-model="model.is_active"><label for="payment_method_active" class="form-check-label">Metode pembayaran aktif</label></div></div>
            <button type="submit" class="btn btn-primary w-100" ng-disabled="saving" ng-bind="saving ? 'Menyimpan...' : (model.id ? 'Simpan perubahan' : 'Tambah metode pembayaran')"></button>
        </form>
    </div></article></div>
    <div class="col-12 col-xl-8"><article class="card sitara-card"><header class="card-header"><div class="d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3"><div><h2 class="sitara-card-title">Daftar metode pembayaran</h2><p class="sitara-card-subtitle"><span ng-bind="activeCount()"></span> aktif dari <span ng-bind="datas.length"></span> metode.</p></div><input type="search" class="form-control form-control-sm" style="max-width:260px" placeholder="Cari kode atau nama metode" ng-model="searchText"></div></header><div class="table-responsive"><table class="table sitara-table mb-0"><thead><tr><th>Kode</th><th>Nama metode</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>
        <tr ng-if="loading"><td colspan="4" class="sitara-empty">Memuat metode pembayaran...</td></tr>
        <tr ng-repeat="item in (filteredDatas=(datas|filter:searchText)) track by item.id"><td class="table-main" ng-bind="item.code"></td><td ng-bind="item.name"></td><td><span ng-class="item.is_active ? 'sitara-status' : 'sitara-status sitara-status-muted'" ng-bind="item.is_active ? 'Aktif' : 'Arsip'"></span></td><td><div class="sitara-row-actions justify-content-end"><button type="button" class="btn btn-sm btn-outline-primary" ng-click="edit(item)">Ubah</button><button type="button" class="btn btn-sm btn-outline-success" ng-if="!item.is_active" ng-click="activate(item)">Aktifkan</button><button type="button" class="btn btn-sm btn-outline-danger" ng-click="hapus(item)">Hapus</button></div></td></tr>
        <tr ng-if="!loading && datas.length===0"><td colspan="4" class="sitara-empty">Belum ada metode pembayaran.</td></tr><tr ng-if="!loading && datas.length && filteredDatas.length===0"><td colspan="4" class="sitara-empty">Tidak ada metode yang sesuai pencarian.</td></tr>
    </tbody></table></div></article></div>
</section>
<script>window.SITARA_PAYMENT_METHOD_CONFIG=<?= json_encode(['baseUrl'=>site_url('keuangan/metode-pembayaran')],JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?>;window.SITARA_CSRF=<?= json_encode(['header'=>$csrfHeader,'hash'=>$csrfHash],JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?>;</script>
<?= $this->endSection() ?>
