<?php
namespace App\Controllers;
use CodeIgniter\Database\BaseConnection;use CodeIgniter\HTTP\ResponseInterface;use RuntimeException;use Throwable;
class AdminUser extends BaseController{
 private BaseConnection $db;public function initController($q,$r,$l):void{parent::initController($q,$r,$l);$this->db=db_connect();}public function index():string{return view('pages/admin/users',['live'=>true,'activeMenu'=>'admin-users','pageTitle'=>'Pengguna Admin','pageSubtitle'=>'Akun administrator dan akses operasional','csrfHeader'=>config('Security')->headerName,'csrfHash'=>csrf_hash()]);}public function read():ResponseInterface{try{return$this->ok($this->db->table('users')->select('id,username,email,full_name,role,is_active,last_login_at,created_at,updated_at')->where('role','ADMIN')->orderBy('full_name')->get()->getResultArray());}catch(Throwable $e){return$this->err($e);}}
 public function create():ResponseInterface{try{$i=$this->payload();$d=$this->clean($i,true);$now=date('Y-m-d H:i:s');$this->db->table('users')->insert([...$d,'password_hash'=>password_hash((string)$i['password'],PASSWORD_DEFAULT),'role'=>'ADMIN','created_at'=>$now,'updated_at'=>$now]);$id=(int)$this->db->insertID();$this->audit('ADMIN_USER_CREATED',$id,null,$this->byId($id));return$this->ok($this->byId($id),'Pengguna admin berhasil dibuat.',201);}catch(Throwable $e){return$this->err($e);}}
 public function update(int $id):ResponseInterface{try{$old=$this->byId($id);if(!$old)throw new RuntimeException('Pengguna admin tidak ditemukan.');$d=$this->clean($this->payload(),false,$id);$auth=session('auth');if(is_array($auth)&&(int)($auth['id']??0)===$id&&!$d['is_active'])throw new RuntimeException('Akun yang sedang digunakan tidak dapat dinonaktifkan.');$this->db->table('users')->where('id',$id)->update([...$d,'updated_at'=>date('Y-m-d H:i:s')]);$this->audit('ADMIN_USER_UPDATED',$id,$old,$this->byId($id));return$this->ok($this->byId($id),'Pengguna admin diperbarui.');}catch(Throwable $e){return$this->err($e);}}
 public function resetPassword(int $id):ResponseInterface{try{$old=$this->byId($id);if(!$old)throw new RuntimeException('Pengguna admin tidak ditemukan.');$i=$this->payload();$p=(string)($i['password']??'');if(strlen($p)<8)throw new RuntimeException('Kata sandi minimal 8 karakter.');$this->db->table('users')->where('id',$id)->update(['password_hash'=>password_hash($p,PASSWORD_DEFAULT),'updated_at'=>date('Y-m-d H:i:s')]);$this->audit('ADMIN_PASSWORD_RESET',$id,null,['password_changed'=>true]);return$this->ok(null,'Kata sandi berhasil diperbarui.');}catch(Throwable $e){return$this->err($e);}}
 private function clean(array $i,bool $create,?int $except=null):array{$u=strtolower(trim((string)($i['username']??'')));$name=trim((string)($i['full_name']??''));$email=strtolower(trim((string)($i['email']??'')))?:null;if(!preg_match('/^[a-z0-9._-]{3,50}$/',$u)||$name===''||($email&&!filter_var($email,FILTER_VALIDATE_EMAIL)))throw new RuntimeException('Username, nama lengkap, atau email tidak valid.');if($create&&strlen((string)($i['password']??''))<8)throw new RuntimeException('Kata sandi minimal 8 karakter.');$q=$this->db->table('users')->groupStart()->where('username',$u);if($email)$q->orWhere('email',$email);$q->groupEnd();if($except)$q->where('id !=',$except);if($q->countAllResults())throw new RuntimeException('Username atau email sudah digunakan.');return['username'=>$u,'email'=>$email,'full_name'=>$name,'is_active'=>(int)($i['is_active']??1)];}private function byId($id):?array{return$this->db->table('users')->select('id,username,email,full_name,role,is_active,last_login_at,created_at,updated_at')->where(['id'=>$id,'role'=>'ADMIN'])->get()->getRowArray();}private function payload():array{$j=$this->request->getJSON(true);return is_array($j)?$j:$this->request->getPost();}private function audit($a,$id,$o,$n):void{$u=session('auth');$this->db->table('audit_logs')->insert(['user_id'=>is_array($u)?($u['id']??null):null,'action'=>$a,'entity_type'=>'users','entity_id'=>$id,'old_values'=>$o?json_encode($o):null,'new_values'=>$n?json_encode($n):null,'ip_address'=>$this->request->getIPAddress(),'created_at'=>date('Y-m-d H:i:s')]);}private function ok($d=null,$m=null,$s=200):ResponseInterface{return$this->response->setStatusCode($s)->setJSON(['ok'=>true,'message'=>$m,'data'=>$d,'csrf'=>['header'=>config('Security')->headerName,'hash'=>csrf_hash()]]);}private function err(Throwable $e):ResponseInterface{return$this->response->setStatusCode(422)->setJSON(['ok'=>false,'message'=>$e->getMessage(),'csrf'=>['header'=>config('Security')->headerName,'hash'=>csrf_hash()]]);}}
