<?php
namespace App\Controllers;
use CodeIgniter\Database\BaseConnection;use CodeIgniter\HTTP\ResponseInterface;use RuntimeException;use Throwable;
class HonorRate extends BaseController{
 private BaseConnection $db;private const ROLES=['PEMBIMBING','PENGUJI'];
 public function initController($q,$r,$l):void{parent::initController($q,$r,$l);$this->db=db_connect();}
 public function index():string{return view('pages/honor/rates',['live'=>true,'activeMenu'=>'honor-rates','pageTitle'=>'Tarif Honor','pageSubtitle'=>'Tarif honor dosen berdasarkan peran dan posisi','roles'=>self::ROLES,'csrfHeader'=>config('Security')->headerName,'csrfHash'=>csrf_hash()]);}
 public function read():ResponseInterface{try{$p=$this->period();$rows=[];if($p)$rows=$this->db->table('honor_rate_settings h')->select('h.*,sp.code program_code,sp.name program_name,at.code activity_code,at.name activity_name')->join('study_programs sp','sp.id=h.study_program_id','left')->join('activity_types at','at.id=h.activity_type_id')->where(['h.academic_period_id'=>$p['id'],'h.is_active'=>1])->orderBy('at.code')->orderBy('h.role_type')->orderBy('h.position_no')->get()->getResultArray();return $this->ok(['activePeriod'=>$p,'rates'=>$rows,'programs'=>$this->db->table('study_programs')->select('id,code,name')->where('is_active',1)->orderBy('code')->get()->getResultArray(),'activityTypes'=>$this->db->table('activity_types')->select('id,code,name')->where('is_active',1)->orderBy('code')->get()->getResultArray()]);}catch(Throwable $e){return$this->err($e);}}
 public function store():ResponseInterface{try{$p=$this->period();if(!$p)throw new RuntimeException('Belum ada periode akademik aktif.');$i=$this->payload();$program=(int)($i['study_program_id']??0)?:null;$activity=(int)($i['activity_type_id']??0);$role=strtoupper(trim((string)($i['role_type']??'')));$position=(int)($i['position_no']??0);$gross=(float)($i['gross_amount']??0);$tax=(float)($i['tax_rate_percent']??0);if($activity<1||!in_array($role,self::ROLES,true)||$position<1||$position>20||$gross<=0||$tax<0||$tax>100)throw new RuntimeException('Jenis kegiatan, peran, posisi, nominal bruto, dan pajak wajib diisi dengan benar.');if($this->db->table('activity_types')->where(['id'=>$activity,'is_active'=>1])->countAllResults()===0)throw new RuntimeException('Jenis kegiatan tidak aktif.');if($program&&$this->db->table('study_programs')->where(['id'=>$program,'is_active'=>1])->countAllResults()===0)throw new RuntimeException('Program studi tidak aktif.');$where=['academic_period_id'=>$p['id'],'activity_type_id'=>$activity,'role_type'=>$role,'position_no'=>$position];$program===null?$where['study_program_id']=null:$where['study_program_id']=$program;$max=$this->db->table('honor_rate_settings')->selectMax('version_no','v')->where($where)->get()->getRow('v');$now=date('Y-m-d H:i:s');$this->db->transStart();$old=$this->db->table('honor_rate_settings')->where($where)->where('is_active',1)->get()->getResultArray();$this->db->table('honor_rate_settings')->where($where)->where('is_active',1)->update(['is_active'=>0,'updated_at'=>$now]);$this->db->table('honor_rate_settings')->insert([...$where,'gross_amount'=>$gross,'tax_rate_percent'=>$tax,'version_no'=>(int)$max+1,'effective_start_date'=>trim((string)($i['effective_start_date']??''))?:null,'effective_end_date'=>trim((string)($i['effective_end_date']??''))?:null,'is_active'=>1,'notes'=>trim((string)($i['notes']??''))?:null,'created_at'=>$now,'updated_at'=>$now]);$id=(int)$this->db->insertID();$this->audit('HONOR_RATE_CREATED',$id,$old?:null,$this->byId($id));$this->db->transComplete();return$this->ok($this->byId($id),'Tarif honor disimpan sebagai versi aktif.',201);}catch(Throwable $e){return$this->err($e);}}
 public function deactivate(int $id):ResponseInterface{try{$old=$this->byId($id);if(!$old)throw new RuntimeException('Tarif honor tidak ditemukan.');$this->db->table('honor_rate_settings')->where('id',$id)->update(['is_active'=>0,'updated_at'=>date('Y-m-d H:i:s')]);$this->audit('HONOR_RATE_DEACTIVATED',$id,$old,$this->byId($id));return$this->ok(null,'Tarif honor dinonaktifkan.');}catch(Throwable $e){return$this->err($e);}}
 private function period():?array{return$this->db->table('academic_periods ap')->select('ap.id,ap.semester_code,ay.code academic_year_code')->join('academic_years ay','ay.id=ap.academic_year_id')->where(['ap.is_active'=>1,'ay.is_active'=>1])->get()->getRowArray();}private function byId(int $id):?array{return$this->db->table('honor_rate_settings')->where('id',$id)->get()->getRowArray();}private function payload():array{$j=$this->request->getJSON(true);return is_array($j)?$j:$this->request->getPost();}private function audit($a,$id,$o,$n):void{$u=session('auth');$this->db->table('audit_logs')->insert(['user_id'=>is_array($u)?($u['id']??null):null,'action'=>$a,'entity_type'=>'honor_rate_settings','entity_id'=>$id,'old_values'=>$o?json_encode($o):null,'new_values'=>$n?json_encode($n):null,'ip_address'=>$this->request->getIPAddress(),'created_at'=>date('Y-m-d H:i:s')]);}private function ok($d=null,$m=null,$s=200):ResponseInterface{return$this->response->setStatusCode($s)->setJSON(['ok'=>true,'message'=>$m,'data'=>$d,'csrf'=>['header'=>config('Security')->headerName,'hash'=>csrf_hash()]]);}private function err(Throwable $e):ResponseInterface{return$this->response->setStatusCode(422)->setJSON(['ok'=>false,'message'=>$e->getMessage(),'csrf'=>['header'=>config('Security')->headerName,'hash'=>csrf_hash()]]);}}
