<?= $this->extend('layouts/main') ?>
<?= $this->section('styles') ?>
<style>[ng-cloak]{display:none!important}.rule-toolbar{background:linear-gradient(135deg,#f8fbff,#eef5fd);border:1px solid #dce9f7;border-radius:.75rem;padding:1rem}.rule-section{border:1px solid #e5eaf0;border-radius:.75rem;padding:1.15rem}.rule-section-blue{background:linear-gradient(120deg,#f3f8ff,#fbfdff 70%);border-color:#dce9f7}.rule-section-title{color:#4b6685;font-size:.75rem;font-weight:700;letter-spacing:.08em;margin-bottom:1rem;text-transform:uppercase}.rule-modal-form{display:flex;flex:1 1 auto;flex-direction:column;max-height:100%;min-height:0}.rule-modal-form>.modal-body{flex:1 1 auto;overflow-y:auto}.rule-modal-form>.modal-footer{background:#fff;box-shadow:0 -.35rem 1rem rgba(31,58,95,.08);z-index:2}</style>
<?= $this->endSection() ?>
<?= $this->section('content') ?>
<?= $this->include('pages/partials/page_heading') ?>
<section ng-controller="aturanKegiatanController" ng-cloak>
    <div class="alert alert-danger" ng-if="errorMessage" ng-bind="errorMessage"></div><div class="alert alert-success" ng-if="successMessage" ng-bind="successMessage"></div>
    <div class="alert alert-warning" ng-if="!loading && !activePeriod">Belum ada periode akademik aktif. Aktifkan periode terlebih dahulu sebelum mengelola aturan.</div>
    <article class="card sitara-card"><header class="card-header border-0 pb-0"><div class="rule-toolbar d-flex flex-column flex-lg-row align-items-lg-center justify-content-between gap-3"><div><h2 class="sitara-card-title">Aturan periode aktif</h2><p class="sitara-card-subtitle mb-0" ng-if="activePeriod"><strong ng-bind="activePeriod.academic_year_code + ' — ' + activePeriod.semester_code"></strong> · <span ng-bind="activeCount()"></span> aktif dari <span ng-bind="datas.length"></span> aturan.</p><p class="sitara-card-subtitle mb-0" ng-if="!activePeriod">Periode aktif belum tersedia.</p></div><div class="d-flex flex-column flex-sm-row gap-2"><input type="search" class="form-control form-control-sm" style="min-width:240px" placeholder="Cari prodi atau kegiatan" ng-model="searchText"><button type="button" class="btn btn-sm btn-outline-primary text-nowrap" ng-click="openCopy()" ng-disabled="!activePeriod || !previousPeriods.length">Salin periode sebelumnya</button><button type="button" class="btn btn-sm btn-primary text-nowrap" ng-click="openCreate()" ng-disabled="!activePeriod">Tambah aturan</button></div></div></header>
        <div class="table-responsive mt-3"><table class="table sitara-table mb-0"><thead><tr><th>Periode</th><th>Program Studi</th><th>Jenis Kegiatan</th><th>Pembimbing</th><th>Penguji</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>
            <tr ng-if="loading"><td colspan="7" class="sitara-empty">Memuat aturan kegiatan...</td></tr>
            <tr ng-repeat="item in (filteredDatas=(datas|filter:searchText)) track by item.id"><td><div class="table-main" ng-bind="item.academic_year_code"></div><div class="small text-gray-600" ng-bind="item.semester_code"></div></td><td><div class="table-main" ng-bind="item.program_code"></div><div class="small text-gray-600" ng-bind="item.program_name"></div></td><td><div class="table-main" ng-bind="item.activity_name"></div><div class="small text-gray-600" ng-bind="item.activity_code"></div></td><td><span ng-bind="item.min_supervisors + '–' + item.max_supervisors"></span> dosen</td><td><span ng-bind="item.min_examiners + '–' + item.max_examiners"></span> dosen<div class="small text-gray-600" ng-if="item.examiner_optional">Opsional</div></td><td><span ng-class="item.is_active ? 'sitara-status' : 'sitara-status sitara-status-muted'" ng-bind="item.is_active ? 'Aktif' : 'Arsip'"></span></td><td><div class="sitara-row-actions justify-content-end"><button class="btn btn-sm btn-outline-primary" type="button" ng-click="edit(item)">Ubah</button><button class="btn btn-sm btn-outline-success" type="button" ng-if="!item.is_active" ng-click="activate(item)">Aktifkan</button><button class="btn btn-sm btn-outline-danger" type="button" ng-click="hapus(item)">Hapus</button></div></td></tr>
            <tr ng-if="!loading && datas.length===0"><td colspan="7" class="sitara-empty">Belum ada aturan kegiatan.</td></tr><tr ng-if="!loading && datas.length && filteredDatas.length===0"><td colspan="7" class="sitara-empty">Tidak ada aturan yang sesuai pencarian.</td></tr>
        </tbody></table></div>
    </article>

    <div class="modal fade" id="activityRuleModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><form class="rule-modal-form" name="activityRuleForm" ng-submit="save(activityRuleForm)" novalidate>
        <div class="modal-header"><div><h2 class="modal-title h5" ng-bind="model.id ? 'Ubah aturan kegiatan' : 'Tambah aturan kegiatan'"></h2><p class="small text-gray-600 mb-0">Tentukan kombinasi akademik dan batas penugasan dosen.</p></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
        <div class="modal-body p-4"><div class="alert alert-danger" ng-if="errorMessage" ng-bind="errorMessage"></div>
            <div class="rule-section rule-section-blue mb-4"><div class="rule-section-title">Kombinasi akademik</div><div class="row g-3"><div class="col-lg-4"><label class="form-label">Periode</label><select name="academic_period_id" class="form-select" ng-model="model.academic_period_id" required><option value="">Pilih periode</option><option ng-repeat="period in periods | filter:{available:true}" ng-value="period.id" ng-bind="period.academic_year_code + ' — ' + period.semester_code"></option></select></div><div class="col-lg-4"><label class="form-label">Program studi</label><select name="study_program_id" class="form-select" ng-model="model.study_program_id" required><option value="">Pilih program studi</option><option ng-repeat="program in programs | filter:{is_active:true}" ng-value="program.id" ng-bind="program.code + ' — ' + program.name"></option></select></div><div class="col-lg-4"><label class="form-label">Jenis kegiatan</label><select name="activity_type_id" class="form-select" ng-model="model.activity_type_id" ng-change="onActivityTypeChange()" required><option value="">Pilih jenis kegiatan</option><option ng-repeat="type in activityTypes | filter:{is_active:true}" ng-value="type.id" ng-bind="type.code + ' — ' + type.name"></option></select></div></div><div class="text-danger small mt-2" ng-if="activityRuleForm.$submitted && (activityRuleForm.academic_period_id.$invalid || activityRuleForm.study_program_id.$invalid || activityRuleForm.activity_type_id.$invalid)">Periode, program studi, dan jenis kegiatan wajib dipilih.</div></div>
            <div class="row g-4"><div class="col-lg-6"><div class="rule-section h-100"><div class="rule-section-title">Batas pembimbing</div><div class="row g-3"><div class="col-6"><label class="form-label">Minimum</label><input name="min_supervisors" type="number" class="form-control" min="1" max="10" ng-model="model.min_supervisors" required></div><div class="col-6"><label class="form-label">Maksimum</label><input name="max_supervisors" type="number" class="form-control" min="1" max="10" ng-model="model.max_supervisors" required></div></div><div class="text-danger small mt-2" ng-if="activityRuleForm.$submitted && model.max_supervisors < model.min_supervisors">Maksimum tidak boleh lebih kecil dari minimum.</div></div></div>
            <div class="col-lg-6"><div class="rule-section h-100"><div class="rule-section-title">Batas penguji</div><div class="row g-3"><div class="col-6"><label class="form-label">Minimum</label><input name="min_examiners" type="number" class="form-control" min="0" max="10" ng-model="model.min_examiners" ng-disabled="!examinerEnabled()" required></div><div class="col-6"><label class="form-label">Maksimum</label><input name="max_examiners" type="number" class="form-control" min="0" max="10" ng-model="model.max_examiners" ng-disabled="!examinerEnabled()" required></div></div><div class="form-check form-switch mt-3"><input id="examiner_optional" class="form-check-input" type="checkbox" ng-model="model.examiner_optional" ng-disabled="!examinerEnabled()"><label for="examiner_optional" class="form-check-label">Penugasan penguji bersifat opsional</label></div><div class="text-danger small mt-2" ng-if="activityRuleForm.$submitted && model.max_examiners < model.min_examiners">Maksimum tidak boleh lebih kecil dari minimum.</div></div></div></div>
            <div class="rule-section mt-4"><div class="row g-3 align-items-end"><div class="col-lg-9"><label class="form-label">Catatan</label><textarea class="form-control" rows="3" maxlength="2000" placeholder="Catatan tambahan (opsional)" ng-model="model.notes"></textarea></div><div class="col-lg-3"><div class="form-check form-switch pb-2"><input id="rule_active" class="form-check-input" type="checkbox" ng-model="model.is_active"><label for="rule_active" class="form-check-label">Aturan aktif</label></div></div></div></div>
        </div>
        <div class="modal-footer"><button type="button" class="btn btn-outline-gray" data-bs-dismiss="modal">Batal</button><button type="submit" class="btn btn-primary px-4" ng-disabled="saving" ng-bind="saving ? 'Menyimpan...' : (model.id ? 'Simpan perubahan' : 'Simpan aturan')"></button></div>
    </form></div></div></div>

    <div class="modal fade" id="copyActivityRuleModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form name="copyRuleForm" ng-submit="copyPrevious(copyRuleForm)" novalidate>
        <div class="modal-header"><div><h2 class="modal-title h5">Salin aturan periode sebelumnya</h2><p class="small text-gray-600 mb-0">Aturan akan disalin ke <strong ng-bind="activePeriod.academic_year_code + ' — ' + activePeriod.semester_code"></strong>.</p></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
        <div class="modal-body p-4"><div class="alert alert-danger" ng-if="errorMessage" ng-bind="errorMessage"></div><div class="alert alert-info small">Kombinasi program studi dan jenis kegiatan yang sudah tersedia pada periode aktif akan dilewati, sehingga tidak ada aturan duplikat.</div><label for="copy_source_period" class="form-label">Periode sumber</label><select id="copy_source_period" name="source_period_id" class="form-select" ng-model="copySourcePeriodId" required><option value="">Pilih periode sebelumnya</option><option ng-repeat="period in previousPeriods" ng-value="period.id" ng-bind="period.academic_year_code + ' — ' + period.semester_code + ' (' + period.rule_count + ' aturan)'"></option></select><div class="text-danger small mt-2" ng-if="copyRuleForm.$submitted && copyRuleForm.source_period_id.$invalid">Pilih periode sumber.</div></div>
        <div class="modal-footer"><button type="button" class="btn btn-outline-gray" data-bs-dismiss="modal" ng-disabled="copying">Batal</button><button type="submit" class="btn btn-primary px-4" ng-disabled="copying" ng-bind="copying ? 'Menyalin...' : 'Salin aturan'"></button></div>
    </form></div></div></div>
</section>
<script>window.SITARA_ACTIVITY_RULE_CONFIG=<?= json_encode(['baseUrl'=>site_url('aturan-kegiatan')],JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?>;window.SITARA_CSRF=<?= json_encode(['header'=>$csrfHeader,'hash'=>$csrfHash],JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?>;</script>
<?= $this->endSection() ?>
