<?= $this->extend('layouts/main') ?>
<?= $this->section('styles') ?><style>[ng-cloak]{display:none!important}</style><?= $this->endSection() ?>
<?= $this->section('content') ?>
<?= $this->include('pages/partials/page_heading') ?>
<section class="row g-3 align-items-start" ng-controller="jenisKegiatanController" ng-cloak>
    <div class="col-12"><div class="alert alert-danger" ng-if="errorMessage" ng-bind="errorMessage"></div><div class="alert alert-success" ng-if="successMessage" ng-bind="successMessage"></div></div>
    <div class="col-12 col-xl-4"><article class="card sitara-card"><header class="card-header d-flex justify-content-between gap-3"><div><h2 class="sitara-card-title" ng-bind="model.id ? 'Ubah jenis kegiatan' : 'Tambah jenis kegiatan'"></h2><p class="sitara-card-subtitle">Field ringkas dapat diisi langsung dari halaman ini.</p></div><button class="btn btn-sm btn-outline-gray" type="button" ng-if="model.id" ng-click="reset()">Batal</button></header><div class="card-body">
        <form name="activityTypeForm" ng-submit="save(activityTypeForm)" novalidate>
            <div class="mb-3"><label for="activity_type_code" class="form-label">Kode</label><input id="activity_type_code" name="code" class="form-control text-uppercase" maxlength="30" placeholder="TUGAS_AKHIR" ng-model="model.code" required ng-pattern="/^[A-Za-z0-9._-]{2,30}$/"><div class="text-danger small mt-1" ng-if="activityTypeForm.$submitted && activityTypeForm.code.$invalid">Kode wajib diisi dengan format yang valid.</div></div>
            <div class="mb-3"><label for="activity_type_name" class="form-label">Nama kegiatan</label><input id="activity_type_name" name="name" class="form-control" minlength="3" maxlength="100" placeholder="Tugas Akhir" ng-model="model.name" required><div class="text-danger small mt-1" ng-if="activityTypeForm.$submitted && activityTypeForm.name.$invalid">Nama kegiatan wajib diisi.</div></div>
            <div class="rounded border bg-gray-50 p-3 mb-3"><div class="form-check form-switch mb-3"><input id="examiner_supported" class="form-check-input" type="checkbox" ng-model="model.examiner_supported"><label for="examiner_supported" class="form-check-label">Mendukung dosen penguji</label></div><div class="form-check form-switch"><input id="activity_type_active" class="form-check-input" type="checkbox" ng-model="model.is_active"><label for="activity_type_active" class="form-check-label">Jenis kegiatan aktif</label></div></div>
            <button type="submit" class="btn btn-primary w-100" ng-disabled="saving" ng-bind="saving ? 'Menyimpan...' : (model.id ? 'Simpan perubahan' : 'Tambah jenis kegiatan')"></button>
        </form>
    </div></article></div>
    <div class="col-12 col-xl-8"><article class="card sitara-card"><header class="card-header"><div class="d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3"><div><h2 class="sitara-card-title">Daftar jenis kegiatan</h2><p class="sitara-card-subtitle"><span ng-bind="activeCount()"></span> aktif dari <span ng-bind="datas.length"></span> jenis kegiatan.</p></div><input type="search" class="form-control form-control-sm" style="max-width:260px" placeholder="Cari kode atau nama" ng-model="searchText"></div></header><div class="table-responsive"><table class="table sitara-table mb-0"><thead><tr><th>Kode</th><th>Nama kegiatan</th><th>Penguji</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>
        <tr ng-if="loading"><td colspan="5" class="sitara-empty">Memuat jenis kegiatan...</td></tr>
        <tr ng-repeat="item in (filteredDatas=(datas|filter:searchText)) track by item.id"><td class="table-main" ng-bind="item.code"></td><td ng-bind="item.name"></td><td><span class="badge" ng-class="item.examiner_supported ? 'bg-info' : 'bg-gray-400'" ng-bind="item.examiner_supported ? 'Didukung' : 'Tidak'"></span></td><td><span ng-class="item.is_active ? 'sitara-status' : 'sitara-status sitara-status-muted'" ng-bind="item.is_active ? 'Aktif' : 'Arsip'"></span></td><td><div class="sitara-row-actions justify-content-end"><button class="btn btn-sm btn-outline-primary" type="button" ng-click="edit(item)">Ubah</button><button class="btn btn-sm btn-outline-success" type="button" ng-if="!item.is_active" ng-click="activate(item)">Aktifkan</button><button class="btn btn-sm btn-outline-danger" type="button" ng-click="hapus(item)">Hapus</button></div></td></tr>
        <tr ng-if="!loading && datas.length===0"><td colspan="5" class="sitara-empty">Belum ada jenis kegiatan.</td></tr><tr ng-if="!loading && datas.length && filteredDatas.length===0"><td colspan="5" class="sitara-empty">Tidak ada data yang sesuai pencarian.</td></tr>
    </tbody></table></div></article></div>
</section>
<script>window.SITARA_ACTIVITY_TYPE_CONFIG=<?= json_encode(['baseUrl' => site_url('kegiatan')], JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?>;window.SITARA_CSRF=<?= json_encode(['header'=>$csrfHeader,'hash'=>$csrfHash], JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?>;</script>
<?= $this->endSection() ?>
