<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<?= $this->include('pages/partials/page_heading') ?>
<section ng-controller="documentTemplateController" ng-cloak>
  <div class="alert alert-danger" ng-if="errorMessage" ng-bind="errorMessage"></div><div class="alert alert-success" ng-if="successMessage" ng-bind="successMessage"></div>
  <article class="card sitara-card mb-4"><div class="card-header"><h2 class="sitara-card-title">Upload template</h2><p class="sitara-card-subtitle mb-0">Template berlaku untuk Prodi yang sedang login.</p></div><div class="card-body"><form name="templateForm" ng-submit="upload(templateForm)" novalidate><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Jenis kegiatan <span class="required-mark">*</span></label><select class="form-select" ng-model="model.activity_type_id" required><option value="">Pilih kegiatan</option><option ng-repeat="x in activityTypes" ng-value="x.id" ng-bind="x.code+' — '+x.name"></option></select></div><div class="col-md-3"><label class="form-label">Jenis dokumen <span class="required-mark">*</span></label><select class="form-select" ng-model="model.document_type" required><option ng-repeat="x in documentTypes" ng-value="x" ng-bind="x"></option></select></div><div class="col-md-3"><label class="form-label">File DOCX <span class="required-mark">*</span></label><input id="document_template_file" type="file" class="form-control" accept=".docx" file-change="selectFile(files)"></div><div class="col-md-2"><button class="btn btn-primary w-100" type="submit" ng-disabled="saving" ng-bind="saving?'Mengunggah...':'Upload'"></button></div></div></form></div></article>
  <article class="card sitara-card"><div class="card-header"><h2 class="sitara-card-title">Template aktif dan isian</h2></div><div class="table-responsive"><table class="table sitara-table mb-0"><thead><tr><th>Jenis kegiatan</th><th>Dokumen</th><th>File</th><th class="text-end">Aksi</th></tr></thead><tbody><tr ng-repeat="t in templates track by t.id"><td ng-bind="t.activity_code+' — '+t.activity_name"></td><td ng-bind="t.document_type"></td><td ng-bind="t.file_name"></td><td class="text-end"><button class="btn btn-sm btn-outline-primary" ng-click="editFields(t)">Atur isian</button> <button class="btn btn-sm btn-outline-warning" ng-click="reupload(t)">Upload ulang</button> <a class="btn btn-sm btn-outline-secondary" ng-href="<?= site_url('template-dokumen/download') ?>/{{t.id}}">Unduh</a></td></tr><tr ng-if="!loading&&!templates.length"><td colspan="4" class="sitara-empty">Belum ada template.</td></tr></tbody></table></div></article>
  <div class="modal fade" id="templateFieldsModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h2 class="modal-title h5">Atur isian template</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-info small">Gunakan field key sebagai placeholder pada DOCX, misalnya <code>${nama_mahasiswa}</code>.</div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Key</th><th>Label</th><th>Sumber</th><th>Source key</th><th>Wajib</th><th></th></tr></thead><tbody><tr ng-repeat="f in fields"><td><input class="form-control" ng-model="f.field_key"></td><td><input class="form-control" ng-model="f.label"></td><td><select class="form-select" ng-model="f.source_type"><option ng-repeat="s in sources" ng-value="s" ng-bind="s"></option></select></td><td><select class="form-select" ng-model="f.source_key" ng-disabled="f.source_type==='MANUAL'||f.source_type==='TEKS_TETAP'"><option value="">Pilih atribut</option><option ng-repeat="(key,label) in sourceOptions(f.source_type)" ng-value="key" ng-bind="label+' ('+key+')'"></option></select></td><td><input type="checkbox" ng-model="f.is_required"></td><td><button class="btn btn-sm btn-outline-danger" ng-click="removeField($index)">Hapus</button></td></tr></tbody></table></div><button class="btn btn-sm btn-outline-primary" ng-click="addField()">Tambah field</button></div><div class="modal-footer"><button class="btn btn-outline-secondary" data-bs-dismiss="modal">Tutup</button><button class="btn btn-primary" ng-click="saveFields()" ng-disabled="saving">Simpan isian</button></div></div></div></div>
</section>
<script>window.SITARA_CSRF=<?= json_encode(['header'=>$csrfHeader,'hash'=>$csrfHash],JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?>;</script>
<?= $this->endSection() ?>
