<?= $this->extend('layouts/main') ?>
<?= $this->section('styles') ?>
<style>
[ng-cloak]{display:none!important}.module-toolbar{background:linear-gradient(135deg,#f8fbff,#eef5fd);border:1px solid #dce9f7;border-radius:.75rem;padding:1rem}.module-form{display:flex;flex-direction:column;width:100%;max-height:calc(100vh - 3.5rem);min-height:0}.module-form>.modal-header,.module-form>.modal-footer{flex:0 0 auto}.module-form>.modal-body{flex:1 1 auto;min-height:0;overflow-y:auto}.module-form>.modal-footer{position:sticky;bottom:0;z-index:3;background:#fff;box-shadow:0 -.3rem 1rem rgba(31,58,95,.12)}#studentActivityModal .modal-content{max-height:calc(100vh - 3.5rem);overflow:hidden}#studentActivityModal .modal-dialog{margin-top:1.75rem;margin-bottom:1.75rem}.assignment-panel{background:#f8fafc;border:1px solid #e3eaf3;border-radius:.75rem;padding:1rem}.required-mark{color:#dc3545;font-weight:700}.required-slot{color:#dc3545;font-size:.75rem;font-weight:600}.ng-submitted .ng-invalid{border-color:#dc3545}@media(max-width:575.98px){.module-form,#studentActivityModal .modal-content{max-height:calc(100vh - 1rem)}#studentActivityModal .modal-dialog{margin:.5rem}}
</style>
<?= $this->endSection() ?>
<?= $this->section('content') ?>
<?= $this->include('pages/partials/page_heading') ?>
<section ng-controller="kegiatanMahasiswaController" ng-cloak>
  <div class="alert alert-danger" ng-if="errorMessage" ng-bind="errorMessage"></div>
  <div class="alert alert-success" ng-if="successMessage" ng-bind="successMessage"></div>
  <div class="alert alert-warning" ng-if="!loading&&!activePeriod">Belum ada periode akademik aktif.</div>

  <ul class="nav nav-tabs mb-3" role="tablist">
    <li class="nav-item"><button type="button" class="nav-link" ng-class="{active:statusTab==='ACTIVE'}" ng-click="setStatusTab('ACTIVE')">Terjadwal &amp; Draft <span class="badge bg-secondary ms-1" ng-bind="statusCount('ACTIVE')"></span></button></li>
    <li class="nav-item"><button type="button" class="nav-link" ng-class="{active:statusTab==='SELESAI'}" ng-click="setStatusTab('SELESAI')">Selesai <span class="badge bg-secondary ms-1" ng-bind="statusCount('SELESAI')"></span></button></li>
    <li class="nav-item"><button type="button" class="nav-link" ng-class="{active:statusTab==='CANCELLED'}" ng-click="setStatusTab('CANCELLED')">Batal <span class="badge bg-secondary ms-1" ng-bind="statusCount('CANCELLED')"></span></button></li>
  </ul>

  <article class="card sitara-card">
    <header class="card-header border-0 pb-0"><div class="module-toolbar d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3"><div><h2 class="sitara-card-title">Kegiatan periode aktif</h2><p class="sitara-card-subtitle mb-0" ng-if="activePeriod" ng-bind="activePeriod.academic_year_code+' — '+activePeriod.semester_code"></p></div><div class="d-flex gap-2"><input type="search" class="form-control form-control-sm" placeholder="Cari NIM, kegiatan, atau jalur" ng-model="searchText"><button type="button" class="btn btn-sm btn-primary text-nowrap" ng-click="openCreate()" ng-disabled="!activePeriod">Tambah kegiatan</button></div></div></header>
    <div class="table-responsive mt-3"><table class="table sitara-table mb-0"><thead><tr><th><input type="checkbox" aria-label="Pilih semua" ng-click="selectAllScheduled()"></th><th>Nomor</th><th>Mahasiswa</th><th>Kegiatan &amp; Jalur</th><th>Tim dosen</th><th>Jadwal</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody><tr ng-if="loading"><td colspan="8" class="sitara-empty">Memuat kegiatan...</td></tr><tr ng-repeat="x in (filteredDatas=(datas|filter:searchText)) track by x.id"><td><input type="checkbox" ng-if="x.scheduled_at" ng-checked="isSelected(x)" ng-click="toggleSelected(x)" aria-label="Pilih mahasiswa"></td><td class="table-main" ng-bind="x.activity_no"></td><td><div class="table-main" ng-bind="x.full_name"></div><small ng-bind="x.nim+' · '+x.program_code"></small></td><td><div class="table-main" ng-bind="x.activity_name"></div><small ng-bind="x.exam_path_name"></small></td><td><div ng-bind="x.supervisor_count+' pembimbing'"></div><small ng-bind="x.examiner_count+' penguji'"></small></td><td ng-bind="x.scheduled_at||'—'"></td><td><span class="sitara-status" ng-bind="statusLabel(x.status)"></span></td><td><div class="sitara-row-actions justify-content-end"><button class="btn btn-sm btn-outline-secondary" ng-if="x.scheduled_at" ng-click="printDocument(x,'nilai')">Nilai</button><button class="btn btn-sm btn-outline-secondary" ng-if="x.scheduled_at" ng-click="printDocument(x,'tunggal')">Berita Acara</button><button class="btn btn-sm btn-outline-primary" ng-if="!isTerminal(x)" ng-click="edit(x)">Ubah</button><button class="btn btn-sm btn-outline-danger" ng-click="hapus(x)">Hapus</button></div></td></tr><tr ng-if="!loading&&!datas.length"><td colspan="8" class="sitara-empty">Belum ada kegiatan mahasiswa.</td></tr></tbody></table></div>
  </article>

  <div class="modal fade" id="studentActivityModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content">
    <form class="module-form" name="studentActivityForm" ng-submit="save(studentActivityForm)" novalidate>
      <div class="modal-header"><div><h2 class="modal-title h5" ng-bind="model.id?'Ubah kegiatan mahasiswa':'Tambah kegiatan mahasiswa'"></h2><p class="small text-gray-600 mb-0">Pembimbing dan penguji mengikuti aturan periode, prodi, dan jenis kegiatan.</p></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div>
      <div class="modal-body p-4"><div class="alert alert-danger" ng-if="errorMessage" ng-bind="errorMessage"></div><div class="alert alert-warning" ng-if="model.locked">Kegiatan sudah masuk proses tagihan atau honor sehingga tidak dapat diubah.</div>
        <fieldset ng-disabled="model.locked"><div class="row g-3">
          <div class="col-lg-5"><label class="form-label">Mahasiswa <span class="required-mark">*</span></label><select name="student_id" class="form-select" ng-model="model.student_id" ng-change="syncRule()" required><option value="">Pilih mahasiswa</option><option ng-repeat="x in students" ng-value="x.id" ng-bind="x.nim+' — '+x.full_name"></option></select><div class="invalid-feedback d-block" ng-if="studentActivityForm.$submitted&&studentActivityForm.student_id.$invalid">Mahasiswa wajib dipilih.</div></div>
          <div class="col-lg-3"><label class="form-label">Jenis kegiatan <span class="required-mark">*</span></label><select name="activity_type_id" class="form-select" ng-model="model.activity_type_id" ng-change="syncRule()" required><option value="">Pilih kegiatan</option><option ng-repeat="x in activityTypes" ng-value="x.id" ng-bind="x.code+' — '+x.name"></option></select><div class="invalid-feedback d-block" ng-if="studentActivityForm.$submitted&&studentActivityForm.activity_type_id.$invalid">Jenis kegiatan wajib dipilih.</div></div>
          <div class="col-lg-2"><label class="form-label">Jalur ujian <span class="required-mark">*</span></label><select name="exam_path_id" class="form-select" ng-model="model.exam_path_id" required><option value="">Pilih jalur</option><option ng-repeat="x in examPaths" ng-value="x.id" ng-bind="x.name"></option></select><div class="invalid-feedback d-block" ng-if="studentActivityForm.$submitted&&studentActivityForm.exam_path_id.$invalid">Jalur ujian wajib dipilih.</div></div>
          <div class="col-lg-2"><label class="form-label">Percobaan ke-</label><input type="number" class="form-control" ng-model="model.attempt_no" readonly><div class="form-text">Terisi otomatis dari riwayat.</div></div>
          <div class="col-lg-8"><label class="form-label">Judul</label><input class="form-control" maxlength="500" ng-model="model.title"></div>
          <div class="col-lg-4"><label class="form-label">Jadwal <span class="required-mark" ng-if="model.status==='TERJADWAL'||model.status==='SELESAI'">*</span></label><input name="scheduled_at" type="datetime-local" class="form-control" ng-model="model.scheduled_at" ng-required="model.status==='TERJADWAL'||model.status==='SELESAI'"><div class="invalid-feedback d-block" ng-if="studentActivityForm.$submitted&&studentActivityForm.scheduled_at.$invalid">Jadwal wajib diisi untuk status Terjadwal atau Selesai.</div></div>
          <div class="col-lg-4"><label class="form-label">Status <span class="required-mark">*</span></label><select name="status" class="form-select" ng-model="model.status" required><option ng-repeat="s in statuses" ng-value="s" ng-bind="statusLabel(s)"></option></select><div class="invalid-feedback d-block" ng-if="studentActivityForm.$submitted&&studentActivityForm.status.$invalid">Status wajib dipilih.</div></div>
          <div class="col-lg-8"><label class="form-label">Catatan</label><textarea class="form-control" rows="2" ng-model="model.notes"></textarea></div>
        </div>
        <div class="alert alert-info mt-4 mb-0" ng-if="model.student_id&&model.activity_type_id&&!activeRule">Aturan kegiatan aktif untuk kombinasi tersebut belum tersedia.</div>
        <div class="assignment-panel mt-4" ng-if="activeRule"><div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h3 class="h6 mb-1">Penugasan pembimbing &amp; penguji</h3><small class="text-gray-600" ng-bind="'Aturan: pembimbing '+activeRule.min_supervisors+'–'+activeRule.max_supervisors+', penguji '+activeRule.min_examiners+'–'+activeRule.max_examiners"></small></div><span class="badge bg-info">Dosen aktif</span></div><div class="row g-3">
          <div class="col-lg-6"><h4 class="h6">Pembimbing</h4><div class="mb-3" ng-repeat="slot in supervisorSlots"><label class="form-label">Pembimbing {{$index+1}} <span class="required-mark" ng-if="$index<activeRule.min_supervisors&&model.status!=='DRAFT'&&model.status!=='CANCELLED'">*</span></label><select class="form-select" ng-model="slot.lecturer_id" ng-required="$index<activeRule.min_supervisors&&model.status!=='DRAFT'&&model.status!=='CANCELLED'"><option value="">Belum dipilih</option><option ng-repeat="d in lecturers" ng-value="d.id" ng-disabled="isLecturerUsed(d.id,slot)" ng-bind="d.full_name+' — '+(d.nidn||d.nip||'Tanpa NIDN/NIP')"></option></select></div><div class="text-gray-500 small" ng-if="!supervisorSlots.length">Aturan tidak memerlukan pembimbing.</div></div>
          <div class="col-lg-6"><h4 class="h6">Penguji</h4><div class="mb-3" ng-repeat="slot in examinerSlots"><label class="form-label">Penguji {{$index+1}} <span class="required-mark" ng-if="$index<activeRule.min_examiners&&model.status!=='DRAFT'&&model.status!=='CANCELLED'">*</span></label><select class="form-select" ng-model="slot.lecturer_id" ng-required="$index<activeRule.min_examiners&&model.status!=='DRAFT'&&model.status!=='CANCELLED'"><option value="">Belum dipilih</option><option ng-repeat="d in lecturers" ng-value="d.id" ng-disabled="isLecturerUsed(d.id,slot)" ng-bind="d.full_name+' — '+(d.nidn||d.nip||'Tanpa NIDN/NIP')"></option></select></div><div class="text-gray-500 small" ng-if="!examinerSlots.length">Aturan tidak memerlukan penguji.</div></div>
        </div></div></fieldset>
      </div>
      <div class="modal-footer"><button type="button" class="btn btn-outline-gray" data-bs-dismiss="modal">Tutup</button><button type="submit" class="btn btn-primary" ng-if="!model.locked" ng-disabled="saving" ng-bind="saving?'Menyimpan...':'Simpan kegiatan & tim dosen'"></button></div>
    </form>
  </div></div></div>

  <div class="d-flex flex-wrap justify-content-end gap-2 mt-3 mb-3"><button type="button" class="btn btn-sm btn-primary" ng-if="selectedIds.length>=2" ng-click="printTeam()">Cetak Berita Acara Tim ({{selectedIds.length}})</button><a class="btn btn-sm btn-outline-primary" href="<?= site_url('kegiatan-mahasiswa/template') ?>">Format Excel</a><button type="button" class="btn btn-sm btn-outline-primary" ng-click="openImport()" ng-disabled="!activePeriod">Import Excel</button></div>
  <div class="modal fade" id="studentActivityImportModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form name="activityImportForm" ng-submit="importExcel(activityImportForm)" novalidate><div class="modal-header"><div><h2 class="modal-title h5">Import kegiatan mahasiswa</h2><p class="small text-gray-600 mb-0">Impor kegiatan beserta tim pembimbing dan penguji.</p></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body p-4"><div class="alert alert-info small">Unduh template terbaru agar sheet referensi sesuai data saat ini. Seluruh baris dibatalkan jika ada satu data yang tidak valid.</div><label for="activity_import_file" class="form-label fw-bold">Pilih berkas .xlsx <span class="required-mark">*</span></label><input id="activity_import_file" type="file" class="form-control" accept=".xlsx" file-change="selectImportFile(files)"><div class="small text-gray-600 mt-2" ng-if="importFile">Siap diimpor: <strong ng-bind="importFile.name"></strong></div><div class="text-danger small mt-2" ng-if="activityImportForm.$submitted&&!importFile">Pilih berkas terlebih dahulu.</div><div class="d-flex justify-content-between align-items-center mt-3"><span class="small text-gray-600">Maksimal 1.000 baris per sheet atau 4 MB.</span><a class="btn btn-sm btn-outline-primary" href="<?= site_url('kegiatan-mahasiswa/template') ?>">Unduh format Excel</a></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-gray" data-bs-dismiss="modal">Batal</button><button type="submit" class="btn btn-primary" ng-disabled="importing" ng-bind="importing?'Mengimpor...':'Import sekarang'"></button></div></form></div></div></div>
</section>
<script>window.SITARA_STUDENT_ACTIVITY_CONFIG=<?= json_encode(['baseUrl'=>site_url('kegiatan-mahasiswa'),'statuses'=>$statuses],JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?>;window.SITARA_CSRF=<?= json_encode(['header'=>$csrfHeader,'hash'=>$csrfHash],JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?>;</script>
<?= $this->endSection() ?>
